import { Header } from "./components/Header";
import { SchemaSection } from "./components/SchemaSection";
import { TargetSummary } from "./components/TargetSummary";
import { useSupabase } from "./hooks/useSupabase";
import type { ReportData } from "./types";

export function App({ reportData }: { reportData: ReportData }) {
  const { analysis, url, apiKey, headers } = reportData;
  const client = useSupabase(url, apiKey, headers);

  return (
    <div className="bg-slate-50 min-h-screen">
      <div className="w-full min-h-screen px-4 py-3">
        <Header
          domain={analysis.summary.domain}
          schemaCount={analysis.schemas.length}
        />

        <TargetSummary
          domain={analysis.summary.domain}
          url={url}
          apiKey={apiKey}
          metadata={analysis.summary.metadata}
          jwtInfo={analysis.summary.jwtInfo}
        />

        <section className="space-y-4">
          <h2 className="text-lg font-bold text-gray-900 mb-3 flex items-center">
            <svg
              className="w-5 h-5 mr-2 text-supabase-green"
              fill="currentColor"
              viewBox="0 0 20 20"
            >
              <path
                fillRule="evenodd"
                d="M3 3a1 1 0 000 2v8a2 2 0 002 2h2.586l-1.293 1.293a1 1 0 101.414 1.414L10 15.414l2.293 2.293a1 1 0 001.414-1.414L12.414 15H15a2 2 0 002-2V5a1 1 0 100-2H3zm11.707 4.707a1 1 0 00-1.414-1.414L10 9.586 8.707 8.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                clipRule="evenodd"
              />
            </svg>
            Database Analysis
          </h2>
          {Object.entries(analysis.schemaDetails).map(
            ([schema, schemaAnalysis]) => (
              <SchemaSection
                key={schema}
                schema={schema}
                analysis={schemaAnalysis}
                client={client}
              />
            ),
          )}
        </section>

        <footer className="mt-6 text-center text-slate-500 text-xs font-mono">
          <p>
            Generated by{" "}
            <a
              href="https://github.com/abhishekg999/supascan"
              target="_blank"
              rel="noopener noreferrer"
              className="text-supabase-green hover:text-emerald-600 transition-colors underline"
            >
              supascan
            </a>{" "}
            - Security analysis tool for Supabase
          </p>
        </footer>
      </div>
    </div>
  );
}
