import type { AnalysisResult } from "./analyzer.service";

export abstract class HtmlRendererService {
  public static generateHtmlReport(result: AnalysisResult): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Supabase Database Analysis Report</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        'supabase-green': '#3ECF8E',
                        'supabase-dark': '#1F2937'
                    }
                }
            }
        }
    </script>
    <style>
        .fade-in { animation: fadeIn 0.5s ease-in; }
        @keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }
        .status-readable { @apply bg-green-100 text-green-800 border-green-200; }
        .status-empty { @apply bg-yellow-100 text-yellow-800 border-yellow-200; }
        .status-denied { @apply bg-red-100 text-red-800 border-red-200; }
    </style>
</head>
<body class="bg-gray-50 min-h-screen">
    <div class="container mx-auto px-4 py-8 max-w-6xl">
        <!-- Header -->
        <header class="bg-white rounded-lg shadow-sm border border-gray-200 p-6 mb-8 fade-in">
            <div class="flex items-center justify-between">
                <div>
                    <h1 class="text-3xl font-bold text-gray-900 mb-2">Supabase Database Analysis</h1>
                    <p class="text-gray-600">Generated on ${new Date().toLocaleString()}</p>
                </div>
                <div class="text-right">
                    <div class="text-sm text-gray-500">Schemas Analyzed</div>
                    <div class="text-2xl font-bold text-supabase-green">${result.schemas.length}</div>
                </div>
            </div>
        </header>

        <!-- Target Summary -->
        <section class="bg-white rounded-lg shadow-sm border border-gray-200 p-6 mb-8 fade-in">
            <h2 class="text-xl font-semibold text-gray-900 mb-4 flex items-center">
                <svg class="w-5 h-5 mr-2 text-supabase-green" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M3 4a1 1 0 011-1h12a1 1 0 011 1v2a1 1 0 01-1 1H4a1 1 0 01-1-1V4zm0 4a1 1 0 011-1h12a1 1 0 011 1v6a1 1 0 01-1 1H4a1 1 0 01-1-1V8z" clip-rule="evenodd"></path>
                </svg>
                Target Summary
            </h2>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                    <label class="text-sm font-medium text-gray-500">Domain</label>
                    <p class="text-lg font-semibold text-gray-900">${this.escapeHtml(result.summary.domain)}</p>
                </div>
                ${this.renderMetadata(result.summary.metadata)}
            </div>
            ${this.renderJWTInfo(result.summary.jwtInfo)}
        </section>

        <!-- Database Analysis -->
        <section class="space-y-6">
            <h2 class="text-xl font-semibold text-gray-900 mb-4 flex items-center">
                <svg class="w-5 h-5 mr-2 text-supabase-green" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M3 3a1 1 0 000 2v8a2 2 0 002 2h2.586l-1.293 1.293a1 1 0 101.414 1.414L10 15.414l2.293 2.293a1 1 0 001.414-1.414L12.414 15H15a2 2 0 002-2V5a1 1 0 100-2H3zm11.707 4.707a1 1 0 00-1.414-1.414L10 9.586 8.707 8.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
                </svg>
                Database Analysis
            </h2>
            ${Object.entries(result.schemaDetails)
              .map(([schema, analysis]) => this.renderSchema(schema, analysis))
              .join("")}
        </section>

        <!-- Footer -->
        <footer class="mt-12 text-center text-gray-500 text-sm">
            <p>Generated by SupaDump - Security analysis tool for Supabase</p>
        </footer>
    </div>

    <script>
        // Add smooth scrolling and interactive features
        document.addEventListener('DOMContentLoaded', function() {
            // Collapse/expand functionality for schema sections
            const toggleButtons = document.querySelectorAll('[data-toggle]');
            toggleButtons.forEach(button => {
                button.addEventListener('click', function() {
                    const target = document.querySelector(this.getAttribute('data-target'));
                    const icon = this.querySelector('svg');
                    if (target.classList.contains('hidden')) {
                        target.classList.remove('hidden');
                        icon.style.transform = 'rotate(180deg)';
                    } else {
                        target.classList.add('hidden');
                        icon.style.transform = 'rotate(0deg)';
                    }
                });
            });
        });
    </script>
</body>
</html>`;
  }

  private static renderMetadata(metadata?: any): string {
    if (!metadata) return "";

    const metadataItems = [];
    if (metadata.service)
      metadataItems.push({ label: "Service", value: metadata.service });
    if (metadata.region)
      metadataItems.push({ label: "Project ID", value: metadata.region });
    if (metadata.title)
      metadataItems.push({ label: "Title", value: metadata.title });
    if (metadata.version)
      metadataItems.push({ label: "Version", value: metadata.version });

    return metadataItems
      .map(
        (item) => `
      <div>
        <label class="text-sm font-medium text-gray-500">${item.label}</label>
        <p class="text-lg font-semibold text-gray-900">${this.escapeHtml(item.value)}</p>
      </div>
    `,
      )
      .join("");
  }

  private static renderJWTInfo(jwtInfo?: any): string {
    if (!jwtInfo) return "";

    return `
      <div class="mt-6 pt-6 border-t border-gray-200">
        <h3 class="text-lg font-medium text-gray-900 mb-3">JWT Token Information</h3>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          ${jwtInfo.iss ? `<div><label class="text-sm font-medium text-gray-500">Issuer</label><p class="text-sm text-gray-900">${this.escapeHtml(jwtInfo.iss)}</p></div>` : ""}
          ${jwtInfo.aud ? `<div><label class="text-sm font-medium text-gray-500">Audience</label><p class="text-sm text-gray-900">${this.escapeHtml(jwtInfo.aud)}</p></div>` : ""}
          ${jwtInfo.role ? `<div><label class="text-sm font-medium text-gray-500">Role</label><p class="text-sm text-gray-900">${this.escapeHtml(jwtInfo.role)}</p></div>` : ""}
          ${jwtInfo.exp ? `<div><label class="text-sm font-medium text-gray-500">Expires</label><p class="text-sm text-gray-900">${new Date(jwtInfo.exp * 1000).toISOString()}</p></div>` : ""}
          ${jwtInfo.iat ? `<div><label class="text-sm font-medium text-gray-500">Issued</label><p class="text-sm text-gray-900">${new Date(jwtInfo.iat * 1000).toISOString()}</p></div>` : ""}
        </div>
      </div>
    `;
  }

  private static renderSchema(schema: string, analysis: any): string {
    const exposedCount = Object.values(analysis.tableAccess).filter(
      (a: any) => a.status === "readable",
    ).length;
    const deniedCount = Object.values(analysis.tableAccess).filter(
      (a: any) => a.status === "denied",
    ).length;
    const emptyCount = Object.values(analysis.tableAccess).filter(
      (a: any) => a.status === "empty",
    ).length;

    return `
      <div class="bg-white rounded-lg shadow-sm border border-gray-200 fade-in">
        <div class="p-6">
          <div class="flex items-center justify-between mb-4">
            <h3 class="text-lg font-semibold text-gray-900">Schema: ${this.escapeHtml(schema)}</h3>
            <button class="text-gray-400 hover:text-gray-600 transition-colors" data-toggle data-target="#schema-${schema}">
              <svg class="w-5 h-5 transition-transform" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path>
              </svg>
            </button>
          </div>
          
          <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
            <div class="text-center p-3 bg-gray-50 rounded-lg">
              <div class="text-2xl font-bold text-green-600">${analysis.tables.length}</div>
              <div class="text-sm text-gray-600">Total Tables</div>
            </div>
            <div class="text-center p-3 bg-gray-50 rounded-lg">
              <div class="text-2xl font-bold text-blue-600">${analysis.rpcs.length}</div>
              <div class="text-sm text-gray-600">RPC Functions</div>
            </div>
            <div class="text-center p-3 bg-gray-50 rounded-lg">
              <div class="text-sm text-gray-600">Access Summary</div>
              <div class="text-xs text-gray-500 mt-1">
                ${exposedCount} exposed • ${emptyCount} empty • ${deniedCount} denied
              </div>
            </div>
          </div>
        </div>

        <div id="schema-${schema}" class="hidden px-6 pb-6">
          <!-- Tables Section -->
          <div class="mb-6">
            <h4 class="text-md font-medium text-gray-900 mb-3 flex items-center">
              <svg class="w-4 h-4 mr-2 text-gray-500" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M3 4a1 1 0 011-1h12a1 1 0 011 1v2a1 1 0 01-1 1H4a1 1 0 01-1-1V4zm0 4a1 1 0 011-1h12a1 1 0 011 1v6a1 1 0 01-1 1H4a1 1 0 01-1-1V8z" clip-rule="evenodd"></path>
              </svg>
              Tables (${analysis.tables.length})
            </h4>
            ${analysis.tables.length > 0 ? this.renderTables(analysis.tables, analysis.tableAccess) : '<p class="text-gray-500 text-sm">No tables found</p>'}
          </div>

          <!-- RPC Functions Section -->
          <div>
            <h4 class="text-md font-medium text-gray-900 mb-3 flex items-center">
              <svg class="w-4 h-4 mr-2 text-gray-500" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M11.3 1.046A1 1 0 0112 2v5h4a1 1 0 01.82 1.573l-7 10A1 1 0 018 18v-5H4a1 1 0 01-.82-1.573l7-10a1 1 0 011.12-.38z" clip-rule="evenodd"></path>
              </svg>
              RPC Functions (${analysis.rpcs.length})
            </h4>
            ${analysis.rpcFunctions.length > 0 ? this.renderRPCFunctions(analysis.rpcFunctions) : '<p class="text-gray-500 text-sm">No RPC functions found</p>'}
          </div>
        </div>
      </div>
    `;
  }

  private static renderTables(
    tables: string[],
    tableAccess: Record<string, any>,
  ): string {
    return `
      <div class="space-y-2">
        ${tables
          .map((table) => {
            const access = tableAccess[table];
            let statusClass = "";
            let statusText = "";
            let statusIcon = "";

            switch (access?.status) {
              case "readable":
                statusClass = "status-readable";
                statusText = "Data exposed";
                statusIcon = "✓";
                break;
              case "empty":
                statusClass = "status-empty";
                statusText = "Empty or RLS protected";
                statusIcon = "○";
                break;
              case "denied":
                statusClass = "status-denied";
                statusText = "Access denied";
                statusIcon = "✗";
                break;
            }

            return `
            <div class="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
              <div class="flex items-center">
                <span class="text-lg mr-3">${statusIcon}</span>
                <span class="font-medium text-gray-900">${this.escapeHtml(table)}</span>
              </div>
              <span class="px-2 py-1 text-xs font-medium rounded-full border ${statusClass}">
                ${statusText}
              </span>
            </div>
          `;
          })
          .join("")}
      </div>
    `;
  }

  private static renderRPCFunctions(rpcFunctions: any[]): string {
    return `
      <div class="space-y-3">
        ${rpcFunctions
          .map(
            (rpc) => `
          <div class="p-4 bg-gray-50 rounded-lg">
            <div class="flex items-center justify-between mb-2">
              <h5 class="font-medium text-gray-900">${this.escapeHtml(rpc.name)}</h5>
            </div>
            ${
              rpc.parameters.length > 0
                ? `
              <div class="mt-2">
                <div class="text-sm font-medium text-gray-700 mb-2">Parameters:</div>
                <div class="space-y-1">
                  ${rpc.parameters
                    .map(
                      (param: any) => `
                    <div class="flex items-center justify-between text-sm">
                      <div class="flex items-center">
                        <span class="font-medium text-gray-900">${this.escapeHtml(param.name)}</span>
                        <span class="text-gray-500 ml-2">${this.escapeHtml(param.type)}</span>
                        ${param.format ? `<span class="text-gray-400 ml-1">(${this.escapeHtml(param.format)})</span>` : ""}
                      </div>
                      <span class="px-2 py-1 text-xs rounded-full ${param.required ? "bg-red-100 text-red-800" : "bg-gray-100 text-gray-600"}">
                        ${param.required ? "required" : "optional"}
                      </span>
                    </div>
                  `,
                    )
                    .join("")}
                </div>
              </div>
            `
                : '<div class="text-sm text-gray-500">No parameters</div>'
            }
          </div>
        `,
          )
          .join("")}
      </div>
    `;
  }

  private static escapeHtml(text: string): string {
    return text
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#39;");
  }
}
